try{
   console.log("I am Your ne Try ")
   throw new Error("I am a Error")
   console.log("I am Your ne Try-1 ")
   }catch{
   console.log("Code Run Poblem")
   }finally{
      console.log("I am your finally Block")
   }